#!/bin/bash

# We expect the following arguments:
# $1 path to .app file
# $2 developer Apple ID email
# $3 developer team ID
# $4 app-specific password (for notarisation)

if [ $# -ne 4 ]
then
    printf "Fatal: received arguments are invalid\n\nUsage:\n  ./sign.sh [path to .app file to sign] [Apple ID email] [Apple Developer team ID] [app-specific password]\n\nNote: check that all spaces are escaped with '\\\\' in the app path\nNote: the app-specific password must be generated by the Apple ID used for signing at https://account.apple.com/account/manage\nNote: use the following command to show Apple codesigning IDs\n  $ security find-identity -v -p codesigning\n"
    exit 1
fi

# We can use this to enforce we're using an absolute path
function get_abs_path() {
    echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

# Bind the arguments provided by the user
FILE_PATH=$(get_abs_path "$1")
DEV_EMAIL="$2"
DEV_TEAM_ID="$3"
APP_PASSWORD="$4"

printf "Attempting to sign $FILE_PATH...\n\n"

# Find the Developer ID Application ID for signing
SIGNING_ID=$(security find-identity -v -p codesigning | grep "Developer\ ID\ Application" | tail -n 1 | cut -c 6-45)

# Sign the application and enabled hardened runtime
codesign --verbose --deep --force --timestamp --options=runtime --sign $SIGNING_ID "$FILE_PATH"

if [ $? -ne 0 ]
then
    printf "\nFailed to sign application\n"
    exit 1
fi

echo

# Zip the .app file to notarise it
zip -r -1 notary_build.zip "$FILE_PATH"

echo

# Notarise the new .zip file — sensitive information here...
xcrun notarytool submit notary_build.zip --wait --apple-id $DEV_EMAIL --team-id $DEV_TEAM_ID --password $APP_PASSWORD

if [ $? -ne 0 ]
then
    printf "\nFailed to notarize\n"
    exit 1
fi

echo

# Remove the temporary notarised zip file
rm -rf notary_build.zip

# Staple the application
xcrun stapler staple "$FILE_PATH"

if [ $? -ne 0 ]
then
    printf "\nFailed to staple: process unsuccessful\n"
    exit 1
fi

echo

# Verify that everything has been signed & notarised
spctl -vvv --assess --type exec "$FILE_PATH"

if [ $? -eq 0 ]
then
    printf "\nProcess successful\n"
    exit 0
else
    printf "\nSigning failed\n"
    exit 1
fi
